return {
    "nvim-treesitter/nvim-treesitter",
    dependencies = "windwp/nvim-ts-autotag",
    opts = {
        ensure_installed = {
            "lua",
            "javascript",
            "typescript",
            "html",
            "vue",
            "css",
            "json",
            "python",
            "bash",
            "markdown",
            "markdown_inline",
            "tsx",
            "c",
            "yaml",
            "toml",
            "vim",
            "vimdoc",
            "query",
        },
    },
}
